
SAMPLES_JSON: 'samples.json'

bamCoverage_args: "--ignoreDuplicates --skipNonCoveredRegions --normalizeUsing CPM --extendReads --binSize 1"
Generich_args: "-j -y -r -e chrM -v -p 0.01 -a 200"

black_list: "data/mm10.blacklist.bed.gz"

### extending summit size to both ends
genome_size: data/mm10_chrom_size.txt
extend_size: 250

## if the samples are clustered together and you want to call peaks for the merged bam from the same cluster
## and recount the reads in peaks for each cell across samples, set this to True
recount_all: True

## parameters for filtering presto  result see scripts/presto_filter.R
presto_filter_workers : 10
presto_filter_n: 2
presto_filter_pct.in.cutoff: 20
presto_filter_pct.each.out.cutoff: 10
presto_filter_max.num.off.target.cells: 100
presto_filter_pct.out.cutoff: 20
presto_filter_padj.cutoff: 0.05
