
SAMPLES_JSON: 'samples.json'

bamCoverage_args: "--ignoreDuplicates --skipNonCoveredRegions --normalizeUsing CPM --extendReads --binSize 1"
Generich_args: "-j -y -r -e chrM -v"

black_list: "data/mm10.blacklist.bed.gz"